version: "3.3"
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        env_file:
            - packages/backend/.env
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
