@startuml VideoCreatorBackend
package domain {
    [video]
    [auth]
}

package common {
    [entity]
    [repository]
    [error]
    [logger]
}

package api {
    [server]
    package resources {
        [router]
        [model]
        [handler]
        [middlewares]
    }
}

package persistence {
    [db]
    [sequelizeRepository]
}

package tests {
    [unit]
    [integration]
    [e2e]
}

package bootstrap {
    [migrations]
    [seeders]
}

domain ...> common
api ...> common
persistence ...> common
api ..> domain
api ..> persistence
@enduml
